# in this notebook we're going to cover the most basic fundamental concepts of tensors using tensorflow

more specifically ,we're going to cover:

- intro to tensors
- getting info from tensors
- manipulation of tensors
- tensors and numpy
- using @tf.functions to speed up our regular python functions
- using gpus with tensorflow(TPUs)
- exercises

## introduction to tensors

In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
#creating tensors with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor ( ndim )
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of vector
vector.ndim

1

In [ ]:
#create a matrix(more than one dimension)
matrix= tf.constant([[10,7],[7,10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 2)

In [ ]:
#create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16) #specify teh data with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#whats' the number of dimensions of another matrix
another_matrix.ndim

2

In [ ]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],
                     [2,5,5]],
                    [[7,8,9],
                     [8,9,0]],
                    [[6,7,8],
                     [1,5,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 5, 5]],

       [[7, 8, 9],
        [8, 9, 0]],

       [[6, 7, 8],
        [1, 5, 7]]], dtype=int32)>

In [ ]:
#dimension of tensor
tensor.ndim

3

#what we've created so far:

- scalar is a single number
- vector is a number with direction
- matrix is a 2-dimensional array of numebers
- tensor is a n-dimensional , where n can be any number

## creating tensors with tf.variable

In [ ]:
tf.Variable


tensorflow.python.ops.variables.Variable

In [ ]:
#create the same as above but with tf.Variable
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try change one of the elements in our changeable tensor
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
#how about we try .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#lets try changing in unchangeable tensor

In [ ]:
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

** Note:**  Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as tensorflow does this for you . However, if in doubt, use tf.constant and change it later if needed

##creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
#create 2 random (but the same) tensors
random1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))


#are they equal

random1, random2 , random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuffle a tensor (valuable when you want to shuffle your datat so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim


2

In [ ]:
#shuffle our non shuffled tensor
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled , seed =42)  # shuffles along first dimension, operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

###other ways to make tensors

In [ ]:
#create a tensor of all ones
tf.ones([10,7])
#tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###you can also turn numpy arrays into tensorflow tensors

the main difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU computing


In [ ]:
import numpy as np
numpy_a=np.arange(1,25,dtype=np.int32)
numpy_a

# x=tf.constant(some_matrix)
# y=tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_a, shape=(2,3,4)) #product of shapes should be equal to length of array
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

#getting information from tensors

when dealing with tensors you probably want to be aware of following attributes:
- shape
- rank
- axis/dimension
- size

In [ ]:
#create a rank 4 tensor (dimension=4)
rank4tensor=tf.zeros([2,3,4,5])
rank4tensor , rank4tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4)

In [ ]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank4tensor.shape , rank4tensor.ndim , tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attributes of our tensor
print("datatype of every element: ",rank4tensor.dtype)
print("number of dimensions/rank : ",rank4tensor.ndim)
print("shape of tensor: ",rank4tensor.shape)
print("elements along 0 axis: ",rank4tensor.shape[0])
print("elements along last axis: ",rank4tensor.shape[-1])
print("total no of elements: ",tf.size(rank4tensor))
print("total no of elements: ",tf.size(rank4tensor).numpy())



datatype of every element:  <dtype: 'float32'>
number of dimensions/rank :  4
shape of tensor:  (2, 3, 4, 5)
elements along 0 axis:  2
elements along last axis:  5
total no of elements:  tf.Tensor(120, shape=(), dtype=int32)
total no of elements:  120


##indexing tensors

In [ ]:
#tensors can be indexed like python lists
rank4tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension from each index except the final one
rank4tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor
rank2tensor=tf.constant([[10,7],[3,4]])
rank2tensor.shape , rank2tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#get the last item of each row of our rank2 tensor
rank2tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#add extra dimension to rank2tensor
rank3tensor=rank2tensor[...,tf.newaxis] #instead of :,:,tf we can use every axis before last one (...,)
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor,axis=-1) #"-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor,axis=0)#"0" means expand the initial axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor,axis=1)#"1" means expand the axis indexed 1

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

### basic operations

 +,  -  ,  *,  /

In [ ]:
tensor=tf.constant([[10,7],
                    [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor*10 , tensor-10 , tensor/10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [ ]:
#we can use tensorflow built in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix Multiplication

in machine learning , matrix multiplication is one of the most common tensor operations

there are two rules out tensors need to fulfill if we are going to matrix multiply them:

- the inner dimension must match
- the resulting matrix has the shape of inner dimensions

In [ ]:
tf.matmul(tensor, tensor) #also works with tf.tensordot

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#matrix multiplication with python operator "@"

tensor*tensor ,  tensor@tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [ ]:
#create a tensor of 3,2
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
y=tf.constant([[6,7],
               [8,9],
               [9,0]])
tf.matmul(x,tf.transpose(y)) , tf.matmul(x, tf.reshape(y,(2,3))) #we can also reshape the y using tf.reshape(y, (2,3)) but it gives different matrix

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[20, 26,  9],
        [46, 60, 27],
        [72, 94, 45]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[24, 25,  8],
        [54, 57, 24],
        [84, 89, 40]], dtype=int32)>)

In [ ]:
tf.transpose(y) , tf.reshape(y,(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[6, 8, 9],
        [7, 9, 0]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[6, 7, 8],
        [9, 9, 0]], dtype=int32)>)

In [ ]:
x , tf.reshape(x, (2,3)) , tf.transpose(x) #for matrix multiplication rules , we should always use transpose and not reshape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

## **the dot product** is the multiplication of 2 matrices that can be done by two ways

- matmul
- tensordot

In [ ]:
tf.tensordot(tf.transpose(x),y, axes=1) , tf.tensordot(x,tf.transpose(y), axes=1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[75, 34],
        [98, 50]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[20, 26,  9],
        [46, 60, 27],
        [72, 94, 45]], dtype=int32)>)

##changing the datatype of our tensor

In [ ]:
b=tf.constant([1.3,1.4])
b.dtype

tf.float32

In [ ]:
c=tf.constant([3,4])
c.dtype

tf.int32

In [ ]:
#changing float32 to float16 (reduced precision) increases performance and speed it on larger datas
b=tf.cast(b,dtype=tf.float16)
b.dtype

tf.float16

In [ ]:
#int32 to float32
c=tf.cast(c,dtype=tf.float32)
c, c.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>,
 tf.float32)

###aggregating tensors

aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
#get the absolute values
d=tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### lets go through the following forms of aggregation

- get the minimum ,maximum
- get the mean of the tensor
- get the sum of the tensor

In [ ]:
#creating a random tensor with values between 0 and 100 of size 50
np.random.seed(42)
e=tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37,  1, 63, 59, 20, 32, 75, 57, 21, 88, 48, 90, 58, 41, 91,
       59, 79, 14, 61, 61, 46, 61, 50, 54, 63,  2, 50,  6, 20, 72, 38])>

In [ ]:
tf.size(e) , e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(e) , np.min(e)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>, 1)

In [ ]:
tf.reduce_max(e) , np.max(e)

(<tf.Tensor: shape=(), dtype=int64, numpy=99>, 99)

In [ ]:
tf.reduce_mean(e) , np.mean(e)

(<tf.Tensor: shape=(), dtype=int64, numpy=50>, 50.84)

In [ ]:
tf.reduce_sum(e) , np.sum(e)

(<tf.Tensor: shape=(), dtype=int64, numpy=2542>, 2542)

In [ ]:
import tensorflow_probability as tfp #needed for finding variance
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=776>

In [ ]:
e=tf.cast(e,dtype=tf.float32)

In [ ]:
tf.math.reduce_std(e)

<tf.Tensor: shape=(), dtype=float32, numpy=27.849854>

In [ ]:
tf.math.reduce_variance(e)  #another method

<tf.Tensor: shape=(), dtype=float32, numpy=775.6144>

In [ ]:
# find the positional max and min
tf.argmax(e) , tf.argmin(e) , e[tf.argmax(e)] , e[tf.argmin(e)]

(<tf.Tensor: shape=(), dtype=int64, numpy=11>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=99.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

## Squeezing a tensor(removing all single dimension)

In [ ]:
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeezed=tf.squeeze(g)
g_squeezed, g_squeezed.shape , g_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]),
 1)

## One Hot Encoding

In [ ]:
#create a list of indices
some_list=[0,1,2,3] #can be red,blue,green, yellow
#one hot encode out list
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value='yeah',off_value='nah' )

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yeah', b'nah', b'nah', b'nah'],
       [b'nah', b'yeah', b'nah', b'nah'],
       [b'nah', b'nah', b'yeah', b'nah'],
       [b'nah', b'nah', b'nah', b'yeah']], dtype=object)>

In [ ]:
tf.one_hot(some_list,depth=3,on_value=2,off_value=0) # thus always go for square

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2],
       [0, 0, 0]], dtype=int32)>

##squaring ,log, sqrt

#can see rest from doc

In [ ]:
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(h,dtype=tf.float32)) #method requires non int type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(h,dtype=tf.float32)) #we require .math. in this and also a non int type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and numpy


In [ ]:
#tensor flow interacts beautifully with numpy array
j=tf.constant(np.array([3,7,10]))

In [ ]:
j

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 10])>

In [ ]:
np.array(j) , type(np.array(j))

(array([ 3,  7, 10]), numpy.ndarray)

In [ ]:
#can also use
j.numpy()

array([ 3,  7, 10])

In [ ]:
j=tf.constant([3])
j.numpy() , j.numpy()[0]


(array([3], dtype=int32), 3)

In [ ]:
#default type of each is slightly different
numpy_j=tf.constant(np.array([3,7,10]))
tensor_j=tf.constant([3,7,10])
#check datatypes of each
numpy_j.dtype , tensor_j.dtype

(tf.int64, tf.int32)

#### Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Aug 13 14:38:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0              26W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

**Note** if you have access to CUDA-enabled Gpu, tensorflow wil automatically use it to access gpu